In [16]:
import pandas as pd
df = pd.read_csv("../data/EGRE_DATOS_ABIERTOS_2020.csv",encoding='latin-1',sep=';')

display(df)

C:\Users\crist\AppData\Local\Temp\ipykernel_11980\4207200106.py:2: DtypeWarning: Columns (7,9,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/EGRE_DATOS_ABIERTOS_2020.csv",encoding='latin-1',sep=';')

,PERTENENCIA_ESTABLECIMIENTO_SALUD,SEXO,GRUPO_EDAD,ETNIA,GLOSA_PAIS_ORIGEN,COMUNA_RESIDENCIA,GLOSA_COMUNA_RESIDENCIA,REGION_RESIDENCIA,GLOSA_REGION_RESIDENCIA,PREVISION,GLOSA_PREVISION,ANO_EGRESO,DIAG1,DIAG2,DIAS_ESTADA,CONDICION_EGRESO,INTERV_Q,PROCED
0,No Pertenecientes al Sistema Nacional de Servi...,HOMBRE,1 a 9,No se identifica con alguna etnia,Chileno,1101,Iquique,1,De Tarapacá,1,FONASA,2020,Q531,NaN,1,1,1,2
1,No Pertenecientes al Sistema Nacional de Servi...,HOMBRE,1 a 9,No se identifica con alguna etnia,Chileno,1101,Iquique,1,De Tarapacá,1,FONASA,2020,Q173,NaN,1,1,1,2
2,No Pertenecientes al Sistema Nacional de Servi...,HOMBRE,1 a 9,No se identifica con alguna etnia,Chileno,1101,Iquique,1,De Tarapacá,1,FONASA,2020,Z412,NaN,1,1,1,2
3,No Pertenecientes al Sistema Nacional de Servi...,HOMBRE,1 a 9,No se identifica con alguna etnia,Chileno,1107,Alto Hospicio,1,De Tarapacá,1,FONASA,2020,N47X,NaN,1,1,1,2
4,No Pertenecientes al Sistema Nacional de Servi...,HOMBRE,1 a 9,No se identifica con alguna etnia,Chileno,1101,Iquique,1,De Tarapacá,1,FONASA,2020,N47X,NaN,1,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1330472,*,*,*,*,*,88888,Extranjero,*,*,*,*,*,O809,NaN,3,1,2,2
1330473,*,*,*,*,*,88888,Extranjero,*,*,*,*,*,O809,NaN,2,1,2,1
1330474,*,*,*,*,*,11101,Coihaique,*,*,*,*,*,G560,NaN,1,1,1,2
1330475,*,*,*,*,*,8112,Hualpén,*,*,*,*,*,P599,NaN,1,1,2,2
1330476,*,*,*,*,*,7301,Curicó,*,*,*,*,*,U071,NaN,7,1,2,2

In [22]:
import polars as pl


#df = pl.read_csv("../data/EGRE_DATOS_ABIERTOS_2020.csv",separator=";")
df = pl.read_csv(
    "../data/EGRE_DATOS_ABIERTOS_2020.csv", 
    separator=";", 
    encoding='latin-1',
    infer_schema_length=False)


df

shape: (1_330_477, 18)
┌─────────────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬──────────┬────────┐
│ PERTENENCIA ┆ SEXO   ┆ GRUPO_EDAD ┆ ETNIA      ┆ … ┆ DIAS_ESTAD ┆ CONDICION_ ┆ INTERV_Q ┆ PROCED │
│ _ESTABLECIM ┆ ---    ┆ ---        ┆ ---        ┆   ┆ A          ┆ EGRESO     ┆ ---      ┆ ---    │
│ IENTO_SA…   ┆ str    ┆ str        ┆ str        ┆   ┆ ---        ┆ ---        ┆ str      ┆ str    │
│ ---         ┆        ┆            ┆            ┆   ┆ str        ┆ str        ┆          ┆        │
│ str         ┆        ┆            ┆            ┆   ┆            ┆            ┆          ┆        │
╞═════════════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪══════════╪════════╡
│ No Pertenec ┆ HOMBRE ┆ 1 a 9      ┆ No se      ┆ … ┆ 1          ┆ 1          ┆ 1        ┆ 2      │
│ ientes al   ┆        ┆            ┆ identifica ┆   ┆            ┆            ┆          ┆        │
│ Sistema N…  ┆        ┆            ┆ con alguna ┆   ┆            ┆            ┆          ┆        │
│             ┆        ┆            ┆ et…        ┆   ┆            ┆            ┆          ┆        │
│ No Pertenec ┆ HOMBRE ┆ 1 a 9      ┆ No se      ┆ … ┆ 1          ┆ 1          ┆ 1        ┆ 2      │
│ ientes al   ┆        ┆            ┆ identifica ┆   ┆            ┆            ┆          ┆        │
│ Sistema N…  ┆        ┆            ┆ con alguna ┆   ┆            ┆            ┆          ┆        │
│             ┆        ┆            ┆ et…        ┆   ┆            ┆            ┆          ┆        │
│ No Pertenec ┆ HOMBRE ┆ 1 a 9      ┆ No se      ┆ … ┆ 1          ┆ 1          ┆ 1        ┆ 2      │
│ ientes al   ┆        ┆            ┆ identifica ┆   ┆            ┆            ┆          ┆        │
│ Sistema N…  ┆        ┆            ┆ con alguna ┆   ┆            ┆            ┆          ┆        │
│             ┆        ┆            ┆ et…        ┆   ┆            ┆            ┆          ┆        │
│ No Pertenec ┆ HOMBRE ┆ 1 a 9      ┆ No se      ┆ … ┆ 1          ┆ 1          ┆ 1        ┆ 2      │
│ ientes al   ┆        ┆            ┆ identifica ┆   ┆            ┆            ┆          ┆        │
│ Sistema N…  ┆        ┆            ┆ con alguna ┆   ┆            ┆            ┆          ┆        │
│             ┆        ┆            ┆ et…        ┆   ┆            ┆            ┆          ┆        │
│ No Pertenec ┆ HOMBRE ┆ 1 a 9      ┆ No se      ┆ … ┆ 1          ┆ 1          ┆ 1        ┆ 2      │
│ ientes al   ┆        ┆            ┆ identifica ┆   ┆            ┆            ┆          ┆        │
│ Sistema N…  ┆        ┆            ┆ con alguna ┆   ┆            ┆            ┆          ┆        │
│             ┆        ┆            ┆ et…        ┆   ┆            ┆            ┆          ┆        │
│ …           ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …        ┆ …      │
│ *           ┆ *      ┆ *          ┆ *          ┆ … ┆ 3          ┆ 1          ┆ 2        ┆ 2      │
│ *           ┆ *      ┆ *          ┆ *          ┆ … ┆ 2          ┆ 1          ┆ 2        ┆ 1      │
│ *           ┆ *      ┆ *          ┆ *          ┆ … ┆ 1          ┆ 1          ┆ 1        ┆ 2      │
│ *           ┆ *      ┆ *          ┆ *          ┆ … ┆ 1          ┆ 1          ┆ 2        ┆ 2      │
│ *           ┆ *      ┆ *          ┆ *          ┆ … ┆ 7          ┆ 1          ┆ 2        ┆ 2      │
└─────────────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴──────────┴────────┘

In [ ]:
from glob import glob
import pandas as pd
df_list=[]
for filename in glob("../data/EGRE_DATOS_ABIERTOS*.csv"):
    temp=pd.read_csv(filename,delimiter=";",encoding="latin-1")
    temp.rename{"PERTENENCIA_ESTABLECIMIENTO_SALU":"PERTENENCIA_ESTABLECIMIENTO_SALUD",inplace=True}
    df_list.append(temp)

df_final = pd.concat(df_list)
df_final["MRUN"] = range(0,df_final.shape[0])

print(df_final.head(3))
print(df_final.tail(3))

C:\Users\crist\AppData\Local\Temp\ipykernel_11980\2891237596.py:5: DtypeWarning: Columns (7,9,11) have mixed types. Specify dtype option on import or set low_memory=False.
  temp=pd.read_csv(filename,delimiter=";",encoding="latin-1")
C:\Users\crist\AppData\Local\Temp\ipykernel_11980\2891237596.py:5: DtypeWarning: Columns (7,9,11) have mixed types. Specify dtype option on import or set low_memory=False.
  temp=pd.read_csv(filename,delimiter=";",encoding="latin-1")

                    PERTENENCIA_ESTABLECIMIENTO_SALU   SEXO GRUPO_EDAD  \
0  No Pertenecientes al Sistema Nacional de Servi...  MUJER      1 a 9
1  No Pertenecientes al Sistema Nacional de Servi...  MUJER      1 a 9
2  No Pertenecientes al Sistema Nacional de Servi...  MUJER      1 a 9

                               ETNIA GLOSA_PAIS_ORIGEN  COMUNA_RESIDENCIA  \
0  No se identifica con alguna etnia           Chileno             1101.0
1  No se identifica con alguna etnia           Chileno             1101.0
2  No se identifica con alguna etnia           Chileno             1101.0

  GLOSA_COMUNA_RESIDENCIA REGION_RESIDENCIA GLOSA_REGION_RESIDENCIA PREVISION  \
0                 Iquique                 1             De Tarapacá         1
1                 Iquique                 1             De Tarapacá         1
2                 Iquique                 1             De Tarapacá         1

  GLOSA_PREVISION ANO_EGRESO DIAG1 DIAG2  DIAS_ESTADA  CONDICION_EGRESO  \
0          FONASA       2019  Q046   NaN            4                 1
1          FONASA       2019  J157   NaN            3                 1
2          FONASA       2019  I288   NaN            6                 1

   INTERV_Q  PROCED PERTENENCIA_ESTABLECIMIENTO_SALUD  MRUN
0         1       2                               NaN     0
1         2       2                               NaN     1
2         2       2                               NaN     2
        PERTENENCIA_ESTABLECIMIENTO_SALU SEXO GRUPO_EDAD ETNIA  \
1330474                              NaN    *          *     *
1330475                              NaN    *          *     *
1330476                              NaN    *          *     *

        GLOSA_PAIS_ORIGEN  COMUNA_RESIDENCIA GLOSA_COMUNA_RESIDENCIA  \
1330474                 *            11101.0               Coihaique
1330475                 *             8112.0                 Hualpén
1330476                 *             7301.0                  Curicó

        REGION_RESIDENCIA GLOSA_REGION_RESIDENCIA PREVISION GLOSA_PREVISION  \
1330474                 *                       *         *               *
1330475                 *                       *         *               *
1330476                 *                       *         *               *

        ANO_EGRESO DIAG1 DIAG2  DIAS_ESTADA  CONDICION_EGRESO  INTERV_Q  \
1330474          *  G560   NaN            1                 1         1
1330475          *  P599   NaN            1                 1         2
1330476          *  U071   NaN            7                 1         2

         PROCED PERTENENCIA_ESTABLECIMIENTO_SALUD     MRUN
1330474       2                                 *  2997654
1330475       2                                 *  2997655
1330476       2                                 *  2997656

In [49]:
print(df_final["SEXO"].value_counts())
#print(df_final.describe())
df_final.groupby("SEXO").agg({"GRUPO_EDAD":"nunique"})

SEXO
MUJER     1701872
HOMBRE    1214398
*           81387
Name: count, dtype: int64

        GRUPO_EDAD
SEXO
*                1
HOMBRE          11
MUJER           11